[package]
name = "lapjv"
version = "0.1.0"
authors = ["Andrii Dmytrenko <andrii.dmytrenko@deliveroo.co.uk>"]
build = "build.rs"

[features]
nightly = []

[dependencies]
ndarray = "0.11"
rand = "0.4"
num-traits = "0.1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }

[build-dependencies]
rustc_version = "0.2"
